### ISSUE TITLE
Bounding Boxes Ordering is wrong

### ISSUE THREAD

**Issue by debparth** [clovaai/CRAFT-pytorch#122]
Hello, Thank Clovaai for your work. I really loved it. I've some problem with the Bounding Box which is getting generated after the text detection in txt file. 

I've already tried to sort it through first y-axis but it didn't work for me.
I know there is already Issue created like this but no one shared the code even if they found it out. So, I think it'll be really better if you **@YoungminBaek** or **@ClovaAIAdmin** can please share some insights regarding this Issue. It'll be of great help.

**Comment by hungtooc** [comment]
its hard to fix, re-order it by algorithm

**Comment by SaeedArisha** [comment]
@debparth Can you share the solution?

**Comment by DhruvAwasthi** [comment]
@debparth @SaeedArisha did you guys solved this issue?

I am facing the same problem, it will really help.

Thanks!
