### ISSUE TITLE
running on a CPU-only machine

### ISSUE THREAD

**Issue by phamdan** [clovaai/CRAFT-pytorch#123]
![image](https://user-images.githubusercontent.com/43165000/97400501-cda9bb00-1921-11eb-9272-9af19e5174c7.png)
fix in line 128 (file test.py)  map_location=torch.device('cpu') but still error. someone help me please. thanks

**Comment by defi0x1** [comment]
do you set --cuda:False in [here](https://github.com/clovaai/CRAFT-pytorch/blob/master/test.py#L50)  ?

**Comment by defi0x1** [comment]
Your device don't have cuda so i think you need set mode run on cpu [here](https://github.com/clovaai/CRAFT-pytorch/blob/master/test.py#L130)

**Comment by phamdan** [comment]
> Your device don't have cuda so i think you need set mode run on cpu [here](https://github.com/clovaai/CRAFT-pytorch/blob/master/test

**Comment by phamdan** [comment]
> Your device don't have cuda so i think you need set mode run on cpu [here](https://github.com/clovaai/CRAFT-pytorch/blob/master/test.py#L130)

very thanks

**Comment by phamdan** [comment]
chào anh ạ . em đang tìm hiểu bài báo này và có đọc về paper và tìm hiểu về
code . mặc dù em đã thử tinh chỉnh các  threshold  rồi mà em vẫn chưa hiểu
kĩ lắm . Anh có thể giải thích cụ thể cho e 3 cái    text_threshold, low_text,
link_threshold  được không ạ . Em cảm ơn a rất nhiều


Vào Th 4, 28 thg 10, 2020 vào lúc 13:40 Đỗ Công Minh <
notifications@github.com> đã viết:
