### ISSUE TITLE
Very slow as loading model in CPU mode by celery

### ISSUE THREAD

**Issue by oohurbert** [clovaai/CRAFT-pytorch#14]
I found it stucked when loading model as a celery task in CPU mode. Such things happens very frequetly as the celery task starts at first  time.
When I use ptrace, I found there're some stuch in "futex", when I use ltrace, I found all the time is memcpy/memset/malloc.
Another celery task is recognition by pytorch model, that's ok.
I wonder if there is a futex in CPU mode when loading the model?

**Comment by brooklyn1900** [comment]
It doesn't work in CPU mode on my computer either.
it shows:
python3 test.py --trained_model=craft_mlt_25k.pth --test_folder=images/
Loading weights from checkpoint (craft_mlt_25k.pth)
Killedmage 1/6: images/chara9.jpg

And it's over with nothing happend

**Comment by oohurbert** [comment]
NO, It can run in CPU mode. But it's very slow when loading the model

**Comment by brooklyn1900** [comment]
I solved the can't work in CPU problem by use smaller images

**Comment by YoungminBaek** [comment]
I do not test a lot in CPU mode, so I do not know the exact problem.

However, it seems that as @brooklyn1900 tried, reducing inference size will help to run in CPU mode.
Please try changing _canvas_size_ augment that indicates the maximum image resolution at inference time.

**Comment by jibolso** [comment]
> It doesn't work in CPU mode on my computer either.
> it shows:
> python3 test.py --trained_model=craft_mlt_25k.pth --test_folder=images/
> Loading weights from checkpoint (craft_mlt_25k.pth)
> Killedmage 1/6: images/chara9.jpg
> 
> And it's over with nothing happend

@brooklyn1900 It works in CPU mode, I think you should set CUDA to false. Atleast that was how I got it to work.
parser.add_argument('--cuda', default=False, type=str2bool, help='Use cuda to train model')
