### ISSUE TITLE
Solution for error on cpu-only machine

### ISSUE THREAD

**Issue by inyong37** [clovaai/CRAFT-pytorch#16]
https://github.com/clovaai/CRAFT-pytorch/blob/ce07620c12f218e67e4ce3cfcd1d9611c37622a9/test.py#L112

When I run test.py on my computer that does not have cuda installed, I get the following error even though `--cuda=False`. I attached the picture, but I also put the error below.

![image](https://user-images.githubusercontent.com/20737479/60943639-8ad56580-a321-11e9-9519-122db3dbb067.png)

```
raise RuntimeError ('Attempting to deserialize object on a CUDA'
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available () is False.
If you are running on a CPU-only machine, please use torch.load with map_location = 'cpu' to map your storages to the CPU.
```
In this case, modify the following line in `main` of `test.py` and the code will run well. Can you add this part to main code for cpu-only users? I put an example below.
```
    net.load_state_dict(copyStateDict(torch.load(args.trained_model)))
```
An example of a modified code:
```
    if args.cuda:
         net.load_state_dict(copyStateDict(torch.load(args.trained_model)))
     else:
         net.load_state_dict(copyStateDict(torch.load(args.trained_model, map_location='cpu')))
```
Thank you for publishing this good STD model.

**Comment by YoungminBaek** [comment]
@inyong37 Thank you for your suggestion.
It seems a nice solution to the part I missed.
I'll update it next time!

**Comment by YoungminBaek** [comment]
@inyong37 The code has been updated according to your example code.
Thanks for your suggestion.

**Comment by Iyyappan-vw** [comment]
if args.cuda:
         net.load_state_dict(copyStateDict(torch.load(args.trained_model)))
     else:
         net.load_state_dict(copyStateDict(torch.load(args.trained_model, map_location='cpu')))

I am already have same given code there but also not solve the error
