### ISSUE TITLE
Why are all the detected areas rectangular, rather than rectangular?

### ISSUE THREAD

**Issue by honghande** [clovaai/CRAFT-pytorch#19]

**Comment by YoungminBaek** [comment]
You mean 'rather than polygon', right?
As with https://github.com/clovaai/CRAFT-pytorch/issues/9, the post-processing related to Polygon will be updated next week after the code has been cleaned up.

**Comment by YoungminBaek** [comment]
@honghande The code has been updated. Thank for your patience.
