### ISSUE TITLE
Are the requirements in requirements.txt outdated/deprecated, no longer available?

### ISSUE THREAD

**Issue by nyck33** [clovaai/CRAFT-pytorch#196]
I tried running this on Colab and had to change the requirements.txt from
```
torch==0.4.1.post2
torchvision==0.2.1
opencv-python==3.4.2.17
scikit-image==0.14.2
scipy==1.1.0
```
to
```
torch
torchvision==0.13
opencv-python
scikit-image
scipy
```
My notebook is messy but you can see it here: https://gist.github.com/nyck33/5c9d191cdf547631f23c9f2d61881379

Currently I am dealing with 
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
So I feel like I change on thing to requirements.txt, notice an error then change it again to fix that error but then a new error pops up.
I don't think that old version of torch is available anymore. 

Can you provide an updated requirement.txt or Colab notework for us to try this out?

**Comment by AtyabOneOrigin** [comment]
Seems the script thinks that your running on a CPU only device, i was having a similar error in a different script and going into the scripts 'parser' section and finding a --cuda command helps, try by setting --cuda=False.
