### ISSUE TITLE
How do you get a gaussian map of the size of the srcimage?

### ISSUE THREAD

**Issue by namedysx** [clovaai/CRAFT-pytorch#21]
Hi,my input image is the size of [547,456],
but the size of output mask is [832,352].
I want to see the affinity map which is same of srcimage's shape.

**Comment by backtime92** [comment]
@namedysx Did you resize the srcimage? Gaussian heatmap and gaussian affinity heatmap size are half of srcimage. The author set the input size is 768 * 768

**Comment by YoungminBaek** [comment]
As @backtime92 answered, the input images are resized to 768x768 for training.
In that case, the size of region and affinity score maps become 384x384.
For the inference stage, you can input an image with any size, and the size of score maps are downscaled to 1/2.

**Comment by alatteaday** [comment]
I have the same problem, when I input an image [108, 25], the output is [96, 32].
and I found the heat map images have kinda space at bottom and right part of the heat maps.
how can I get a map image having the size of the corresponding input without the spaces?
![res_TZ_ts_easy_lr_7_mask](https://user-images.githubusercontent.com/75011343/128327783-a059d3a5-a902-497e-8d53-b892ebaf742f.jpg)
