### ISSUE TITLE
How to define the 'adjacent character box pair' when generating gt affinity boxes?

### ISSUE THREAD

**Issue by sonack** [clovaai/CRAFT-pytorch#22]
![image](https://user-images.githubusercontent.com/12935189/61435806-ed56e300-a96b-11e9-8d2d-ada11aa3b2bb.png)

![image](https://user-images.githubusercontent.com/12935189/61435824-fcd62c00-a96b-11e9-9509-0513d5d35396.png)
I am confused about the 'adjacent judgement' when I only have char-level bbox, did you mean only consider the adjacent char bbox within one word-level? If two char bbox close but in vertical direction, we don't consider them as adjacent, am I right?

**Comment by YoungminBaek** [comment]
@sonack You are right. We consider the adjacent char bounding boxes only if the characters belong to the same word instance.  If two char boxes are close but do not make up a word, these are not considered to be adjacent.
