### ISSUE TITLE
Providing pretrained model currently support Korean Lang text detection?

### ISSUE THREAD

**Issue by heartcored98** [clovaai/CRAFT-pytorch#23]
I see that providing a pretrained model is trained on IC13 and IC17 dataset. 
Do these datasets include image samples within Korean? 

Since I would like to adapt your model to recognize the quotation written in Korean. 
Do you think pretrained model would work?

**Comment by YoungminBaek** [comment]
Yes, the pre-trained model was trained on multi lanauge dataset, so will work in Korean too.
FYI, IC17 dataset includes several scripts such as  Arabic, Latin, Chinese, Japanese, Korean, and Bangla.
https://rrc.cvc.uab.es/?ch=8&com=tasks
