### ISSUE TITLE
I'm confused about model architecture

### ISSUE THREAD

**Issue by spydr1** [clovaai/CRAFT-pytorch#24]
https://github.com/clovaai/CRAFT-pytorch/blob/7afb2bdb62f7715662bc2457cb42d32ce5d18e2c/craft.py#L58-L80

Last stage's output shape is (H/32,W/32)
F.interpolate is look like up-sampling function.
Your model have three up-sampling function. 
But predict shape is (H/2,W/2). 
how can do this ?

So i have a question about this 

https://github.com/clovaai/CRAFT-pytorch/blob/7afb2bdb62f7715662bc2457cb42d32ce5d18e2c/basenet/vgg16_bn.py#L42-L45

self.slice5 - Does layer have down-sampling ?

**Comment by YoungminBaek** [comment]
@spydr1 Thank you for error correction!
We did not realize that the size of the feature layers has been miscalculated.

Actually the conv stage2 is not the output of the max pooling but the last layer of the convolutions 2_2 in vgg16 in the following code.

https://github.com/clovaai/CRAFT-pytorch/blob/7afb2bdb62f7715662bc2457cb42d32ce5d18e2c/basenet/vgg16_bn.py#L32-L39
```
0 Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
1 BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
2 ReLU(inplace)
3 Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
4 BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
5 ReLU(inplace)
6 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
7 Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
8 BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
9 ReLU(inplace)
10 Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
11 BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
12 ReLU(inplace)
13 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
14 Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
15 BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
16 ReLU(inplace)
17 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
18 BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
19 ReLU(inplace)
20 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
21 BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
22 ReLU(inplace)
23 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
24 Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
25 BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
26 ReLU(inplace)
27 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
28 BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
29 ReLU(inplace)
30 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
31 BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
32 ReLU(inplace)
33 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
34 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
35 BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
36 ReLU(inplace)
37 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
38 BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
```

Therefore, the size should be like below.
![image](https://user-images.githubusercontent.com/13248735/62366260-5d1abf80-b561-11e9-81f2-d1f8cd87bf08.png)

Thank you for your correction again, and sorry for the confusion.

**Comment by YanShuang17** [comment]
@YoungminBaek Hello author, I found there is something wrong in your comment above:
conv stage2 is not the output of the max pooling but the last layer of the convolutions 2_2,yeah, this is right !
but, according to your print info above:
conv stage3 is the output of the conv3_2,  not conv3_3;
conv stage4 is the output of the conv4_2,  not conv4_3;
conv stage5 is the output of the conv5_2,  not conv5_3;
is it your miscalculation or my misunderstanding?

**Comment by YanShuang17** [comment]
in addition, could you tell me the value of sigma in gaussian kernel?
