### ISSUE TITLE
The network structure in the code is different from that in the paper

### ISSUE THREAD

**Issue by namedysx** [clovaai/CRAFT-pytorch#32]
In paper, VGG_bn output size is w/32, h/32, 512,
in code VGG_bn output 'h_fc7'(in vgg16_bn.py) like this,
relu2_2 shape: torch.Size([1, 384, 384, 128])
relu3_2 shape: torch.Size([1, 192, 192, 256])
relu4_3 shape: torch.Size([1, 96, 96, 512])
relu5_3 shape: torch.Size([1, 48, 48, 512])
fc7 shape: torch.Size([1, 48, 48, 1024]),
input size is 786, 786, 3   
784/48 =16...

**Comment by namedysx** [comment]
and it is min-size fearture map in this structure which in code

**Comment by YanShuang17** [comment]
refer to [issue24](https://github.com/clovaai/CRAFT-pytorch/issues/24)

**Comment by YoungminBaek** [comment]
@YanShuang17 Thanks you for answering instead.
Sorry to confuse you, @namedysx.
