### ISSUE TITLE
How to evaluate text detection results without word level annotation

### ISSUE THREAD

**Issue by KosukeHao** [clovaai/CRAFT-pytorch#35]
Dataset like ICDAR2015 has word level annotation, so that craft can be evaluated easily by IoU.

How can we evaluate  the performance of craft with annotation like text region? Such as labeling the entire text area "Hello World!" with a single rectangle.

It is my pleasure to get the answers.

**Comment by YoungminBaek** [comment]
@KosukeHao 
I do not understand 'the annotation like text region'. Did you mean the line-level annotation, not the word-level?

In the case of line-level annotation such as CTW-1500 dataset, we used additional _LinkRefiner_ network to combine the multiple words separated by spaces. You can refer to the appendix section, pp. 11-12 in our paper https://arxiv.org/pdf/1904.01941.pdf.

**Comment by IamAVB** [comment]
Hi @YoungminBaek ,
     Thanks for releasing CRAFT model. Is there plan to release LinkRefiner model?

**Comment by YoungminBaek** [comment]
@IamAVB Sure. I will update the repo to add _LinkRefiner_ model soon.

**Comment by lamhoangtung** [comment]
> @IamAVB Sure. I will update the repo to add _LinkRefiner_ model soon.

Looking for it <3

**Comment by YoungminBaek** [comment]
The _LinkRefiner_ model for long text detection has been updated in the commit https://github.com/clovaai/CRAFT-pytorch/commit/3cd65f5a7bb6cbba8ed3844e385aaffe7d7e103e.
I hope this can help you.

**Comment by lamhoangtung** [comment]
@YoungminBaek Just a quick question. What is the Loss Function that you used to train the LinkRefiner model ?

**Comment by KosukeHao** [comment]
Thank you very much for your answer! @YoungminBaek

**Comment by iknoorjobs** [comment]
Hi @YoungminBaek @IamAVB 
Were you able to run the LinkRefiner model for line-level annotations?
I tried this command
`python test.py --cuda=False --trained_model='craft_mlt_25k.pth' --test_folder='CRAFT-pytorch/test' --refine refiner_model='craft_mlt_25k.pth'`

It showed the following error
`RuntimeError: Error(s) in loading state_dict for RefineNet:Missing key(s) in state_dict: .........`

Am I missing something? Thanks for help.
