### ISSUE TITLE
Extracting the detected boxes

### ISSUE THREAD

**Issue by deepseek** [clovaai/CRAFT-pytorch#39]
@YoungminBaek Now that Craft have detected the boxes and saved them into a `.txt` file, can you add a script to extract/crop the detected boxes into images.

**Comment by akarazniewicz** [comment]
This is trivial, You can use something like this:

```python


# convert bounding shape to bounding box
def bounding_box(points):
            points = points.astype(np.int16)
            x_coordinates, y_coordinates = zip(*points)
            return [(min(x_coordinates), min(y_coordinates)), (max(x_coordinates), max(y_coordinates))]

# detection
bboxes, score_text = test_net(net, image, args.text_threshold, args.link_threshold, args.low_text, args.cuda)

for i, bbs in enumerate(bboxes):
            crop = bounding_box(bbs)
            cropped = image[crop[0][1]:crop[1][1],crop[0][0]:crop[1][0]]
            cv2.imwrite(result_folder + '/res_' + filename + '_cropped_' + str(i) + '.png', cropped)

```

**Comment by deepseek** [comment]
@akarazniewicz how to implement your code in the `test.py` script.
Can you modify `test.py` and post it here.

**Comment by kalai2033** [comment]
@YoungminBaek, @ClovaAIAdmin ...... First of all thanks very much for your model. I have used your pretrained model for text extraction. I have got the bounding box coordinates and converted the polygons to rectangles for cropping the text area in the image. The resulted bounding boxes are shuffled and i could not sort it out. As per my understanding, the boxes are sorted on the basis of top_left_y. But when there is a presence of curved text, i need to sort before passing it to text extraction model.


![image](https://user-images.githubusercontent.com/49688647/64231526-2af9d600-cef0-11e9-8889-43f2d5a0e908.png)

     In this case the word order detected is, Australian->Collection->vine->old. But the expected output is Australian->old->vine->collection.

**Comment by deepseek** [comment]
@akarazniewicz can you share your email so i can contact you

**Comment by jussyr** [comment]
This is covered in Issue #8 :
Take a look at the [warpPerspectivePoly](https://github.com/clovaai/CRAFT-pytorch/issues/8#issuecomment-508986974) comment.

**Comment by deepseek** [comment]
@jussyr yup, thats what I am talking about.
can you integrate it into a script that takes the .txt+jpg and extract the boxes?

**Comment by YoungminBaek** [comment]
@akarazniewicz Thanks for giving the good solution.
@deepseek I think you can easily implement the code for cropping word images by referring the snippets.

**Comment by erikestany** [comment]
Hi,

I also need to export the detected boxes from the Colab notebook, but I don't understand how to do it.

With the code suggested by @akarazniewicz, I get this error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-7-b12c4da62a69>](https://localhost:8080/#) in <module>()
      7 
      8 # detection
----> 9 bboxes, score_text = test_net(net, image, args.text_threshold, args.link_threshold, args.low_text, args.cuda)
     10 
     11 for i, bbs in enumerate(bboxes):

NameError: name 'test_net' is not defined
```

What am I doing wrong?

Thank you so much!

**Comment by Ravi4103** [comment]
Can anyone share the colab implemented CRAFT on pytorch?
