### ISSUE TITLE
The reimplementation results are not good

### ISSUE THREAD

**Issue by backtime92** [clovaai/CRAFT-pytorch#41]
![image](https://user-images.githubusercontent.com/29878249/64306454-5ef2fb00-cfc5-11e9-947a-134fce483f92.png)
This is my reimplementation results. I found that it is not good enough and recall is much lower than your results. Could you give me some advice or matters needing attention. Thanks a lot

**Comment by deepseek** [comment]
@mayank-git-hub @YoungminBaek @s3nh @RubanSeven

**Comment by mayank-git-hub** [comment]
@backtime92 @deepseek the repo does not contain the training code yet.

I have not been able to reach results even close to the ones mentioned in the paper. many important but vital details have been left out in the paper which is needed to reimplement it.

**Comment by backtime92** [comment]
@mayank-git-hub I will release it as soon as possible. Can we chat with email?

**Comment by mayank-git-hub** [comment]
> @mayank-git-hub I will release it as soon as possible. Can we chat with email?

Sure, mine is mayank25031998@gmail.com

**Comment by backtime92** [comment]
@mayank-git-hub ok

**Comment by backtime92** [comment]
I have released the whole code, any issues are welcome.

**Comment by YoungminBaek** [comment]
@backtime92 Thank you for releasing the training code of CRAFT.
I'll check them and write some comments in your repo!

**Comment by backtime92** [comment]
@YoungminBaek ok,i will upload the new code

**Comment by backtime92** [comment]
@YoungminBaek I have upload the new code, thanks for your excellent work and your help.
