### ISSUE TITLE
The code for training

### ISSUE THREAD

**Issue by Kimcher** [clovaai/CRAFT-pytorch#42]
thanks for you model. and where can I get the code for training?

**Comment by YoungminBaek** [comment]
Duplicated issue (https://github.com/clovaai/CRAFT-pytorch/issues/2). 
Sorry for your inconvenience.

@backtime92 kindly published the reimplementation of CRAFT with training codes.
You can refer to the repo https://github.com/backtime92/CRAFT-Reimplementation.

**Comment by felipecicero** [comment]
Excuse me, I'm looking at the code for the training and I noticed that the part that calculates the affinity maps is commented, why? According to the article, this segment of the affinity maps is very important for the word generation, I ended up confused.
