### ISSUE TITLE
Parallel inference

### ISSUE THREAD

**Issue by ajinkya933** [clovaai/CRAFT-pytorch#44]
In the demo app I see the images are being queued and inference is taken on them one after another. Is it possible to run inference in parallel and not in queue as shown in the demo. Please explain ?

**Comment by YoungminBaek** [comment]
I think running the inference in parallel is difficult due to the post-processing step, which is performed in CPU unless you use multi-processing technique.
However, the batch-processing of deep networks is possible within a memory limit.

**Comment by tringn** [comment]
hi @YoungminBaek ,
Thanks for your great work.
In the inference code, I see that every image with different size will be resized into its own corresponding size. (`(1073, 1077, 3)` resized to `(1280, 1280, 3)`, `(1280, 960, 3)` resized to `(1280, 960, 3)`)
How can we run it in batch (all images need to have same shape)?
Thank you very much.
