### ISSUE TITLE
Is there a way to get character-level annotations?

### ISSUE THREAD

**Issue by Jopkirs** [clovaai/CRAFT-pytorch#46]
Is there some way I can get character-level annotation boxes as output instead of the word-level annotation ones?

**Comment by hetul-patel** [comment]
In the **craft_utils.py**  file, try replacing this line 

### text_score_comb = np.clip(text_score + link_score, 0, 1)

With this line 

### text_score_comb = np.clip(text_score, 0, 1).

You will get character level bounding boxes for sufficiently large characters.

**Comment by deepseek** [comment]
@hetul-patel how about line-level?

**Comment by YoungminBaek** [comment]
@deepseek The line-level bounding box can be obtained by an additional network called as LinkRefiner. I'll upload the LinkRefiner model soon.

**Comment by mrocr** [comment]
@YoungminBaek Thank you, I'll be waiting.

**Comment by deepseek** [comment]
@YoungminBaek Thank you, I'll be waiting.

**Comment by Jopkirs** [comment]
@hetul-patel Thank you for your solution. It worked.

**Comment by lerndeep** [comment]
I am searching link refiner training code. how can I get the link refiner training code?
