### ISSUE TITLE
Please help for below argumnets

### ISSUE THREAD

**Issue by nbhupendra** [clovaai/CRAFT-pytorch#51]
Plz help me to understand the meaning of below arguments-
--text_threshold: text confidence threshold
--low_text: text low-bound score
--link_threshold: link confidence threshold
@ClovaAIAdmin @YoungminBaek

**Comment by YacobBY** [comment]
From what I've been able to understaind myself:

**text_threshold** = Certainity required for a something to be classified as a letter. The higher this value the clearer characters need to look.

**low_text** =  Amount of boundary space around the letter. The higher this value the less space

**link_threshold** =  Amount of distance allowed between two characters for them to be seen as a single word.

**Comment by otutsukihyuuga** [comment]
> **low_text** = Amount of boundary space around the letter/word when the coordinates are returned

What exactly is meant by boundary space? is it the area of boundary box??
I'm sorry if it's a stupid question but i can't seem to get my head around it
I wanted to make an ocr which detected each character individually so for that keeping link_threshold as 0 might do the trick but i wanted to know what exactly does low_text do. Can anyone please let me know??
