### ISSUE TITLE
about the checkpoint

### ISSUE THREAD

**Issue by sszzy0317** [clovaai/CRAFT-pytorch#55]
the checkpoint you shared may be trained by the English dataset only, I saw your demo the model can 
recognize the Japanese correctly.would you shared the checkpoint trained by the Japanese dataset.

**Comment by YoungminBaek** [comment]
@sszzy0317

The trained model we uploaded was trained with multi-language dataset including Japanese.
IC17-MLT dataset includes Chinese, Japanese, Korean, English, French, Arabic, Italian, German and Indian. (https://rrc.cvc.uab.es/?ch=8)

You can use the first link from the table.
https://github.com/clovaai/CRAFT-pytorch#test-instruction-using-pretrained-model
