### ISSUE TITLE
Execution in docker image issue vgg16_bn.py

### ISSUE THREAD

**Issue by loopedice** [clovaai/CRAFT-pytorch#57]
Hey, so I got this working on my mac pretty easily. However I just can't seem to get it to work on a docker image. 

It seems to crash when executing this line https://github.com/clovaai/CRAFT-pytorch/blob/master/basenet/vgg16_bn.py#L61

Tried to debug through, but don't really have any experience with pdb so got nowhere there. I suspect my Dockerfile isn't setup right. Did anyone manage to get this working or have similar issues? My dockerfile is below.

```
FROM ubuntu:18.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
 
# Install tools
RUN apt-get update \
        && apt-get --yes install \
        wget \
        curl \
        ca-certificates \
        sudo \
        git \
        bzip2 \
        libx11-6 libglib2.0-0 \
        libsm6 libxext6 libxrender-dev \
        && rm -rf /var/lib/apt/lists/*
 

 # Create a working directory
RUN mkdir /app
WORKDIR /app


# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Install Miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
 
# Set environment PATH
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

RUN conda install --yes python=3.6

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD ["python", "test.py"]
```

**Comment by loopedice** [comment]
Do you mind sharing your Dockerfile setup for this?

**Comment by lamhoangtung** [comment]
@loopedice. Sure, it's extremely simple:
```dockerfile
FROM python:3.6.8

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    wget \
    nano \
    htop \
    tmux \
    unzip \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

COPY . /code
WORKDIR /code
RUN pip install -r requirements.txt

CMD python server.py
```

**Comment by loopedice** [comment]
@lamhoangtung Thanks for that. It still seems to be failing. I will try again later tonight on my windows machine with docker, and see if that doesn't produce a crash.

**Comment by lamhoangtung** [comment]
> @lamhoangtung Thanks for that. It still seems to be failing. I will try again later tonight on my windows machine with docker, and see if that doesn't produce a crash like my mac.

Both Mac and linux works fine for me :P

**Comment by loopedice** [comment]
It's so strange 😬 Maybe my docker config has limited resources?

**Comment by loopedice** [comment]
Resolved my issue. Problem was that I was using 0.4.1 and not 0.4.1.post2. So I just went to 1.0.0 due to errors in pip not finding 0.4.1.post2
