### ISSUE TITLE
Is there a way to get line-level annotations?

### ISSUE THREAD

**Issue by ajinkya933** [clovaai/CRAFT-pytorch#58]
I observed that word and character level annotations are supported, but is there a way to get line level annotations, for example all the words on a single line are annotated in a single bounding box  ?

**Comment by yyyash8** [comment]
> I observed that word and character level annotations are supported, but is there a way to get line level annotations, for example all the words on a single line are annotated in a single bounding box ?

Did you find any way to do that?

**Comment by mostafahadian** [comment]
You can use --refine option.
