### ISSUE TITLE
How long does it take to release the train?

### ISSUE THREAD

**Issue by backtime92** [clovaai/CRAFT-pytorch#6]
I am try to reimplement the model,but there are some details that i am not clear. Are there some reference about train code which can give me ？

**Comment by zhenx** [comment]
co-ask

**Comment by zacharywhitley** [comment]
co-co-ask :)

**Comment by Yifan-Zhao** [comment]
co*n-ask :):):)

**Comment by wrongbattery** [comment]
co*n-ask :)*n

**Comment by YoungminBaek** [comment]
As stated in https://github.com/clovaai/CRAFT-pytorch/issues/2, due to company regulations, we have no plan to disclose training codes. I'm sorry to disappoint you. Please leave a detailed inquiry in the issue.

**Comment by sonack** [comment]
> As stated in #2, due to company regulations, we have no plan to disclose training codes. I'm sorry to disappoint you. Please leave a detailed inquiry in the issue.

I think it is better to update the README file if you may not release the training code soon, the [training part](https://github.com/clovaai/CRAFT-pytorch#training) of README is misleading! 

Thanks for your excellent work!

**Comment by YoungminBaek** [comment]
@sonack Thank you for clarification. I should have updated README for train part.
Again, sorry for not releasing train code.
If you have any questions about training, I will be happy to answer them.
