### ISSUE TITLE
Is CRAFT multilingual?

### ISSUE THREAD

**Issue by ThisIsIsaac** [clovaai/CRAFT-pytorch#60]
1. Is CRAFT capable of learning detection for different langauges?

2. Can a single model learn two or more languages? If so, how many have you tried?

3. In the Naver demo page, from the UI perspective, there seems to be two models: one for English + Korean and another for Chinese +Japanese (please correct me if I'm wrong). Is it because you have empirically found English and Korean to be trainable in a single model?

**Comment by lamhoangtung** [comment]
1. In my opinion, Yes
2. Yes, i’ve tried English + Japanese, English + Vietnamese
3. I’m not sure but I think separated model is definitely better for production environment

**Comment by ThisIsIsaac** [comment]
@lamhoangtung  thanks!

> 2. Yes, i’ve tried English + Japanese, English + Vietnamese

Did different' combination of languages effect performance?

**Comment by YoungminBaek** [comment]
@ThisIsIsaac 

1. Yes. The provided model was trained with multi-language dataset, IC17-MLT.

2. As @lamhoangtung  mentioned, it's possible to some extent.
But I'd like to note that, some characters written cursively (e.g. Bangla, Arabic, etc) are difficult to be learned at a character-level using a weakly-supervised manner. From our observation, box generation was possible, but the individual characters were not clearly separated.

3. In the demo page, we use a single model for text detection. Our model seems to be robust to the full-width characters in Chines, Japanese, and Korean.
