### ISSUE TITLE
about LinkRefiner

### ISSUE THREAD

**Issue by cuongdxk57** [clovaai/CRAFT-pytorch#64]
Hi @YoungminBaek, thanks  for your works.
I have a question for you about ground truth of LinkRefiner, that's from  each center line, are you  generate Gaussian heat map for it or set to 1?

**Comment by YoungminBaek** [comment]
@cuongdxk57 
For training LinkRefiner, we do not need to generate Gaussian heatmap. The center lines of LinkRefiner didn't come from the characters. They are directly obtained from polygon-shaped ground truth in CTW-1500 dataset.
