### ISSUE TITLE
Ignore verticle text and output only horizhontal text

### ISSUE THREAD

**Issue by ajinkya933** [clovaai/CRAFT-pytorch#65]
I observed in the demo that, both vertical and horizontal text are detected. How can I Ignore vertical texts and output only horizontal text.

**Comment by YoungminBaek** [comment]
@ajinkya933 
The recognition for horizontal and vertical texts is not possible in the original CRAFT. You need more information about the orientation of each character. And, we are integrating the character orientation in CRAFT. Please stay tuned.
