### ISSUE TITLE
Word level detection

### ISSUE THREAD

**Issue by yashkant** [clovaai/CRAFT-pytorch#67]
Hi, 

Thanks for the great repository. For my use case, I want to detect instances of individual words as opposed to the whole sentence within a single bbox, is there any parameter I could tune to fix this issue? 

For example in the image below at the bottom-most detected box contains multiple words, I would like to have one bbox per-word, how could I generate them? 

Cheers! 

![res_4581975775_5aca0a300b_o](https://user-images.githubusercontent.com/17530895/68186517-580b4900-ff72-11e9-8b09-17893594bc3e.jpg)

**Comment by YoungminBaek** [comment]
@yashkant Sorry for the late reply.

I do not understand the result image.
Do you use _linkrefiner_ for combining word bounding boxes?
In your case for detecting individual words, you will get a better result by not using both polygon output and link refiner.

These are the results I get from your image.
![image](https://user-images.githubusercontent.com/13248735/70117941-1cb38580-16aa-11ea-9c8f-89f7d79db277.png)
![image](https://user-images.githubusercontent.com/13248735/70117954-276e1a80-16aa-11ea-9efe-10b49e7b8e53.png)
