### ISSUE TITLE
Is the model the same of the demo website?

### ISSUE THREAD

**Issue by ziudeso** [clovaai/CRAFT-pytorch#7]
Is the model provided the same as https://demo.ocr.clova.ai/ ?
I can't recognize numbers correctly

**Comment by ziudeso** [comment]
sorry my fault

**Comment by YoungminBaek** [comment]
The architecture is the same, but the dataset used for training is different.
More private data is used for the web demo model.

**Comment by AyushP123** [comment]
@YoungminBaek,  Did you mean it for the text recognition network only or for both the networks??
