### ISSUE TITLE
How to set the parameters of ic15 model?

### ISSUE THREAD

**Issue by ZhouEnjoysL** [clovaai/CRAFT-pytorch#70]
For the given ic15 model, I want to get the same result of paper. So how should I set the parameters in the testing code?

When setting text_threshold as 0.9, I get my best result:
Pre: 0.88    Rec:  0.82    Hmean: 0.85

Thanks for your reply.

**Comment by YoungminBaek** [comment]
@ZhouEnjoysL Sorry for the late reply. The parameters for the paper were 0.85, 0.5, and 0.2 for text_threshold, low_text, and link_threshold, respectively. However, after the code was cleaned up, the post-processing for box generation was modified. You will get a slightly different result using this repo although the model and the parameters are identical.
