### ISSUE TITLE
How to get single character bounding boxes?

### ISSUE THREAD

**Issue by antocapp** [clovaai/CRAFT-pytorch#71]
Hello, thanks for sharing this repository. 

How can I extract single-character bounding boxes from heatmaps?

Thanks

**Comment by lamhoangtung** [comment]
Set `--link_threshold` to `99999999` and you are good to go

**Comment by antocapp** [comment]
Hi @lamhoangtung thanks for the answer; I've tried setting that threshold but in order to get the single bounding boxes I needed to separate the contours of the characters, otherwise I'd obtain always one single connected component. So in conclusion I've set the text threshold (and the low text too - just to get smaller characters and points) to 0.4, while keeping link threshold very high. 

Thanks! 

PS. This is just an idea: would it be better to retrieve char bounding boxes by computing the entire bounding box for a word (so as it happens now with link threshold set to a valure between [0,1]) and then use the link heatmap just to divide the entire bounding box into several bounding boxes corresponding to characters just by using straight line in correspendence with link heatmaps peaks?

**Comment by YoungminBaek** [comment]
@antocapp Thanks for sharing your idea. If you need an application that requires character boxes, your approach definitely works.

The reason why we output only word-level results is just we did not find many applications that need explicit character boxes. If you have such requirements, it will be great to make character bounding boxes by your suggestion.
