### ISSUE TITLE
The network architecture still confused.

### ISSUE THREAD

**Issue by KevinNuNu** [clovaai/CRAFT-pytorch#73]
![image](https://user-images.githubusercontent.com/34083603/70119264-d4de2f80-16a4-11ea-915b-b77856e2a4eb.png)

@YoungminBaek 
Hi, the issue #24 u update the network architecture, but it's still confusing.
https://github.com/clovaai/CRAFT-pytorch/blob/e332dd8b718e291f51b66ff8f9ef2c98ee4474c8/craft.py#L37-L41
https://github.com/clovaai/CRAFT-pytorch/blob/e332dd8b718e291f51b66ff8f9ef2c98ee4474c8/craft.py#L58-L64

the upconv1 input channel should be 1024+512,
so it seems the last stage of VGG16-BN (Conv Stage6) should be (h/16×w/16×1024), which is the output of self.slice5. Do u think so?
https://github.com/clovaai/CRAFT-pytorch/blob/e332dd8b718e291f51b66ff8f9ef2c98ee4474c8/basenet/vgg16_bn.py#L60-L73

**Comment by wk-ff** [comment]
I agree with you.

I find 5 slices in `vgg16_bn.py`, instead of 6 stages.
Since the output of first slice is the output of conv2_2, the outputs of 5 stages are (h/2xw/2x128), (h/4xw/4x256), (h/8xw/8x512), (h/16xw/16x512), (h/16xw/16x1024).

This is my opinion.
