### ISSUE TITLE
Does center of a triangle mean incenter?

### ISSUE THREAD

**Issue by shitvuive123** [clovaai/CRAFT-pytorch#75]
<img width="155" alt="Screen Shot 2019-12-10 at 9 19 49 AM" src="https://user-images.githubusercontent.com/58715057/70489499-89a5a000-1b2e-11ea-87dc-7069c0eb4f8f.png">
I wonder that is center of  triangle in paper mean incenter or centroid or circumcenter?

**Comment by YoungminBaek** [comment]
Centroid. Sorry for the late reply.
