### ISSUE TITLE
About WebDemo link 

### ISSUE THREAD

**Issue by zcswdt** [clovaai/CRAFT-pytorch#76]
I used the online demo link (https://demo.ocr.clova.ai/) you provided and the test model ICDAR13 + ICDAR2017 you provided to test the same picture, and got different results. Obviously, the online demo link is more accurate. Can you give me a model of your online demo? Thank you!

**Comment by YoungminBaek** [comment]
The demo model was trained on our private datasets, so the release of the model is prohibited. Please excuse me for this.
