### ISSUE TITLE
Character Segmentation from Image

### ISSUE THREAD

**Issue by dhruvsatyapanthi007** [clovaai/CRAFT-pytorch#80]
Hi,

I have a image which is a output of text detector and contains a word in it. I want to perform character level segmentation in this image. Please help me to proceed.

Thanks in Advance

**Comment by YoungminBaek** [comment]
Your comment is the key idea of CRAFT text detector. But, I feel sorry for your inconvenience due to the lack of training code here. You can check out the reimplementation repo by https://github.com/backtime92/CRAFT-Reimplementation.
Good luck!
