### ISSUE TITLE
TypeError: Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)

### ISSUE THREAD

**Issue by xxxpsyduck** [clovaai/CRAFT-pytorch#84]
Loading weights from checkpoint (craft_mlt_25k.pth)
Loading weights of refiner from checkpoint (craft_refiner_CTW1500.pth)
Traceback (most recent call last):08014857_IMG_0236.jpeg
  File "test.py", line 169, in <module>
    file_utils.saveResult(image_path, image[:,:,::-1], polys, dirname=result_folder)
  File "/home/aiteammor/Downloads/CRAFT-pytorch/file_utils.py", line 62, in saveResult
    cv2.polylines(np.array(img), [poly.reshape((-1, 1, 2))], True, color=(0, 0, 255), thickness=2)
TypeError: Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)

**Comment by gvdsand** [comment]
I had the same issue with some of my images. For whatever reasons it helped me to use
img = np.ascontiguousarray(img, dtype=np.uint8)
instead of
img = np.array(img)
in line 43 of file_utils.py

**Comment by AzwadAbid** [comment]
@gvdsand Thanks mate. It solved my issue as well.

**Comment by xxxpsyduck** [comment]
@gvdsand Worked. Thanks. 
P/s: You should make a pull request to fix this

**Comment by xxxpsyduck** [comment]
@YoungminBaek should be aware of this

**Comment by AzwadAbid** [comment]
@xxxpsyduck , I just did. Mentioned @gvdsand on it.

**Comment by YoungminBaek** [comment]
Thanks for the good solution. I was not aware of it. Many thanks!

**Comment by hoangduyloc** [comment]
Thank you!

**Comment by EricCousineau-TRI** [comment]
> For whatever reasons it helped me to use [...]

I tried to briefly explain it here: https://stackoverflow.com/a/50128836/7829525 - if anyone reads this and has a more precise answer, input on that SO thread is always welcome ;)

**Comment by dgdgksj** [comment]
> I had the same issue with some of my images. For whatever reasons it helped me to use img = np.ascontiguousarray(img, dtype=np.uint8) instead of img = np.array(img) in line 43 of file_utils.py

Thank you!

**Comment by dgdgksj** [comment]
Thank you!
