### ISSUE TITLE
Matching Claimed performance

### ISSUE THREAD

**Issue by Suhruth9** [clovaai/CRAFT-pytorch#85]
I have tried to check the model's performance on ICDAR15 test data. I got H mean of 79 at first. After changing the canvas_size to 2240 as mentioned in the paper, it increased to 84.5 but still short of the claimed performance in the paper which is 86.9. What am I missing and what are further changes required to reach 86.9?

**Comment by YoungminBaek** [comment]
As replied in https://github.com/clovaai/CRAFT-pytorch/issues/38#issuecomment-533800045, the postprocessing code was modified during the code clearing, so there is a performance gap even when using the same model.

Also, we observed that IoU evaluation was very sensitive to the thresholds. In the experiment, our thresholds were 0.85, 0.5 and 0.2 for text threshold, low text and link threshold, respectively.

I hope this will help your experiment.

**Comment by pustar** [comment]
> I have tried to check the model's performance on ICDAR15 test data. I got H mean of 79 at first. After changing the canvas_size to 2240 as mentioned in the paper, it increased to 84.5 but still short of the claimed performance in the paper which is 86.9. What am I missing and what are further changes required to reach 86.9?

Have you reached 86.9 or near by?  Would you please share your parameters setting?
