### ISSUE TITLE
Can I get the affinity/rotation degree of each bounding box? 

### ISSUE THREAD

**Issue by ShroukMansour** [clovaai/CRAFT-pytorch#88]
Hey there, I want to get the affinity/rotation degree of each bounding box so that, take the average rotation degree and rotate the image by it in order to fix the rotated images. Any help @YoungminBaek  @ClovaAIAdmin

**Comment by YoungminBaek** [comment]
This is a good question from the perspective of text recognition. However, CRAFT does not predict the character orientation, only region and affinity scores. This is a limitation of CRAFT detector. We are also working on estimating the rotation degree to fix the rotated text images.

In our experience, predicting orientation at a pixel level through output channel expansion worked well to some extent.

**Comment by jezebleum** [comment]
did you end up finding a solution to this? i'm working on a comparable case to enhance classification of text but haven't been able to find a solution for it yet.
