### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'

### ISSUE THREAD

**Issue by samrudh** [clovaai/CRAFT-pytorch#89]
torchvision Pillow compatibility fails

**Comment by samrudh** [comment]
Solution, as I found [here](https://github.com/python-pillow/Pillow/issues/4130), is to  either downgrade Pillow to  6.1 or use __version__ instead of PILLOW_VERSION

`pip install Pillow==6.1`

**Comment by hugovk** [comment]
Alternatively: [torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

https://github.com/pytorch/vision/issues/1712

**Comment by YoungminBaek** [comment]
This issue has been open for a while. So I close now.
Thanks for giving solutions~ :)
