### ISSUE TITLE
How to get polygonal text instance output rather than BB?

### ISSUE THREAD

**Issue by ziudeso** [clovaai/CRAFT-pytorch#9]
I suppose it is in the getDetBoxes_core function, can you kindly elucidate? 
Thanks in advance

**Comment by YoungminBaek** [comment]
Post-processing for polygon representation is not currently in the repository. I'm still having problems with some cases so I'll release it as soon as performance improves.

**Comment by ziudeso** [comment]
Thanks for the response, can I kindly ask you to share the code anyway for people like me that want to try it regardless of its efficiency? It would be fantastic, thanks! Or if you feel more comfortable can you send it to my email (francesco.delog@gmail.com) so that we at the university can have a look at it?
Thanks in advance for your cooperation

**Comment by YoungminBaek** [comment]
@ziudeso I will update the code until next week. I appreciate your patience.

**Comment by YoungminBaek** [comment]
@ziudeso The polygon generation function has been added. 
Please try and give feedback. Thanks!
