### ISSUE TITLE
How can I get the text preceded by the api?

### ISSUE THREAD

**Issue by JoelUser** [clovaai/CRAFT-pytorch#92]
only the heat map and the score map are displayed in the output folder, but I wanted to know how I can get the output text.

**Comment by ShroukMansour** [comment]
If you want the text-img, then you can crop the original image with each bounding box provided by the test_net function

**Comment by JoelUser** [comment]
I was referring to how to copy the text from the image.

**Comment by YoungminBaek** [comment]
As @ShroukMansour replied, you need to crop the original image with each bounding box, and recognize them. This repo is only for text detection, and the repo for text recognition is [here](https://github.com/clovaai/deep-text-recognition-benchmark). Good luck!
