### ISSUE TITLE
Segmentation at character level question

### ISSUE THREAD

**Issue by anavc94** [clovaai/CRAFT-pytorch#98]
Hi,

first of all, CRAFT works pretty good, congratulations!

I have another question related to character level segmentation which I have not find on issues.
I am trying to perform character level segmentation so my approach to get it easily was setting --link_threshold to a high value, such as 9999999. It does perform character level detection at most cases. However, they are some letters that it is still joining in a single bounding box. I have looked at the heatmaps and it does seem that these character could have been succesfully separated. 

This is an example:

![res_862](https://user-images.githubusercontent.com/37656547/81545549-5a16f000-9379-11ea-99c1-21edc7389fcd.jpg)

![res_862_mask](https://user-images.githubusercontent.com/37656547/81545550-5b481d00-9379-11ea-9b12-8fcef70d9e1f.jpg)

For example, the digits in the first column "126" have a common bounding box, but in the heatmap it looks like they have different peaks.

Can you please explain to me why is this happening and if i can segment characters in this kind of cases? I would appreciate it. Thank you in advance and thank you for your work.

Regards!

**Comment by sjang42** [comment]
Even if the red and green area looks different to us, it could become same after binarizing with a threshold. I suggest you to increase the threshold til the green line not considered as text area.
